"""
02_train.py
===========
Trains 6 algorithms at every endpoint by patient-level nested cross-validation.

Algorithms: LinReg (baseline), ElasticNet, Random Forest, XGBoost, CatBoost, MLP.

Strategy (NESTED CV - no hyperparameter leakage):
  The OUTER CV (N_FOLDS patient-level folds) produces the out-of-fold
  predictions, one per patient. For each outer fold:
    1) Optuna optimises the hyperparameters through an INNER CV
       (N_INNER_FOLDS folds) built ONLY on the training part of that outer fold.
       The outer test fold is never seen during tuning.
    2) The model is trained with those best parameters on the whole outer
       training set and predicts the outer test fold, giving unbiased OOF
       predictions.
  Hyperparameters may therefore differ from one outer fold to the next.
  (LinReg has no hyperparameter, so a plain outer CV is equivalent to nesting.)

  DEPLOYABLE MODEL: after the nested CV, one more Optuna tuning is run (inner CV
  over all patients), then the model is refitted on all patients with those best
  parameters. Those deployable hyperparameters serve the delivered model only,
  never the OOF predictions.

Outputs in MODELS_DIR/<endpoint>/:
  - linreg.joblib, elasticnet.joblib, rf.joblib,
    xgboost.json, catboost.cbm, mlp.pt      (final deployable models)
  - preprocessor.joblib                     (fitted on all patients)
  - best_params_<algo>.json                 (deployable params, per-outer-fold
                                             params, and inner CV RMSE)
  - oof_predictions.csv                     (record_id, repeat, fold, source,
                                             y_true, and one column per algorithm)

LEAKAGE DIAGNOSTIC: the OOF metrics printed here are computed only on the "real"
targets (a real measurement inside the window, see targets_source.csv). The
"model" targets, imputed by the trajectory model of 01_prepare_target.py, are
used for TRAINING (training folds) but never evaluated, otherwise performance
would be inflated by smoothed, denoised targets. The `source` column of
oof_predictions.csv allows the metrics to be re-sliced afterwards.
"""
import json
import warnings
from pathlib import Path

import joblib
import numpy as np
import optuna
import pandas as pd
import torch
import torch.nn as nn
import xgboost as xgb
from catboost import CatBoostRegressor, Pool
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import ElasticNet, LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from config import (
    PREP_DIR, MODELS_DIR, SEED, N_FOLDS, N_REPEATS, N_INNER_FOLDS, N_THREADS,
    OPTUNA_N_TRIALS, OPTUNA_N_TRIALS_BY_ALGO, OPTUNA_TIMEOUT,
    OPTUNA_PRUNER_STARTUP_TRIALS, OPTUNA_PRUNER_WARMUP_STEPS,
    CATBOOST_FIXED, CATEGORICAL_FEATURES,
    XGBOOST_FIXED, RF_FIXED, ELASTICNET_FIXED,
    MLP_MAX_EPOCHS, MLP_PATIENCE, MLP_BATCH_SIZE,
)
from utils import (ensure_dir, regression_metrics, kfold_patients,
                   repeated_kfold_patients)

warnings.filterwarnings("ignore", category=UserWarning)
optuna.logging.set_verbosity(optuna.logging.WARNING)

torch.manual_seed(SEED)
np.random.seed(SEED)
# Fixed share of the cores for torch when several scenarios run in parallel,
# consistent with the n_jobs / thread_count of the other algorithms.
torch.set_num_threads(N_THREADS)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ============================================================
# Loading and per-endpoint preparation
# ============================================================
def load_prep():
    X = pd.read_csv(PREP_DIR / "features.csv", index_col=0)
    y = pd.read_csv(PREP_DIR / "targets.csv", index_col=0)
    # Target provenance (real / model / NaN). It may be missing if the targets
    # were generated by an older version of 01_prepare_target.py, in which case
    # every target is evaluated.
    src_path = PREP_DIR / "targets_source.csv"
    y_source = pd.read_csv(src_path, index_col=0) if src_path.exists() else None
    if y_source is None:
        print("  ! targets_source.csv missing -> evaluating on ALL targets "
              "(real + model). Rerun 01_prepare_target.py for the real-only diagnostic.")
    return X, y, y_source


def get_endpoint_data(X, y_col):
    """Restrict to the patients with a non-NaN y at this endpoint."""
    y = y_col.dropna()
    common = X.index.intersection(y.index)
    return X.loc[common].copy(), y.loc[common].copy()


def real_eval_index(X, y_source, endpoint):
    """Index of the patients whose target at this endpoint is a REAL measurement
    (Case 1), the only ones on which OOF performance is evaluated. If the
    provenance is unknown, fall back to every patient of X."""
    if y_source is None or endpoint not in y_source.columns:
        return X.index
    real_ids = y_source.index[y_source[endpoint] == "real"]
    return X.index[X.index.isin(real_ids)]


def _as_repeat_frame(oof):
    """Normalise an OOF object to a DataFrame (index=record_id, columns=repeats).

    A Series (single partition) is accepted for backward compatibility and
    becomes column 0, so n_repeats=1 behaves exactly as a single partition."""
    if isinstance(oof, pd.Series):
        return oof.to_frame(0)
    return oof


def report_oof(tag, y, oof, eval_idx):
    """Print the OOF metric evaluated ONLY on `eval_idx` (real targets) and,
    as a leakage diagnostic, the metric over ALL targets (real + model).
    Returns the real-only metrics dict.

    Under repeated CV the metrics are POOLED across repetitions, each patient
    contributing r predictions. At r=1 this is identical to a single partition.
    The between-repetition dispersion is printed as well, giving a direct read
    of the instability due to the partition."""
    oof = _as_repeat_frame(oof)
    reps = list(oof.columns)

    yr = y.loc[eval_idx]
    y_pool = pd.concat([yr] * len(reps), ignore_index=True)
    p_pool = pd.concat([oof.loc[eval_idx, r] for r in reps], ignore_index=True)
    mr = y_pool.notna() & p_pool.notna()
    if int(mr.sum()) == 0:
        print(f"        {tag}: no real target to evaluate (n_real=0).")
        return None
    m_real = regression_metrics(y_pool[mr], p_pool[mr])

    y_all = pd.concat([y] * len(reps), ignore_index=True)
    p_all = pd.concat([oof[r] for r in reps], ignore_index=True)
    ma = y_all.notna() & p_all.notna()
    m_all = regression_metrics(y_all[ma], p_all[ma])

    n_real = int(mr.sum()) // len(reps)
    print(f"        OOF real-only (n={n_real}) -> "
          f"RMSE={m_real['rmse']:.3f}  MAE={m_real['mae']:.3f}  R2={m_real['r2']:.3f}"
          f"   | all incl. model (n={int(ma.sum()) // len(reps)}): R2={m_all['r2']:.3f}")
    if len(reps) > 1:
        rmses = []
        for r in reps:
            pr = oof.loc[eval_idx, r]
            m = yr.notna() & pr.notna()
            rmses.append(regression_metrics(yr[m], pr[m])["rmse"])
        print(f"        -> {len(reps)} repetitions: RMSE "
              f"{np.mean(rmses):.3f} +/- {np.std(rmses, ddof=1):.3f} "
              f"[{np.min(rmses):.3f}, {np.max(rmses):.3f}]")
    return m_real


# ============================================================
# Preprocessor shared by MLP / LinReg
# ============================================================
def build_preprocessor(feature_columns):
    cat_cols = [c for c in CATEGORICAL_FEATURES if c in feature_columns]
    num_cols = [c for c in feature_columns if c not in cat_cols]
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])
    cat_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ])
    return ColumnTransformer([("num", num_pipe, num_cols), ("cat", cat_pipe, cat_cols)])


def _prep_catboost_df(df):
    """CatBoost: impute the categorical columns with the 'missing' string."""
    out = df.copy()
    for c in CATEGORICAL_FEATURES:
        if c in out.columns:
            out[c] = out[c].fillna("missing").astype(str)
    return out


def _early_stop_split(ids, seed):
    """90/10 split of a set of IDs, for internal early stopping."""
    rng = np.random.default_rng(seed)
    arr = np.array(ids)
    rng.shuffle(arr)
    cut = int(0.9 * len(arr))
    return arr[:cut], arr[cut:]


# ============================================================
# Generic NESTED CV engine
# ============================================================
# Every tunable algorithm exposes three callables:
#   tune_fn(X, y, inner_folds)       -> (params_dict, inner_cv_rmse)
#       runs Optuna minimising the inner CV RMSE (inner_folds); returns params
#       directly usable by fitpred_fn / final_fn.
#   fitpred_fn(X, y, tr, te, params) -> preds (np.array aligned on te)
#       trains on the IDs `tr` and predicts the IDs `te`.
#   final_fn(X, y, params, out_dir)  -> None
#       deployable refit on all patients, then serialises the model.
def run_nested_cv(name, tune_fn, fitpred_fn, final_fn, X, y, outer_folds, out_dir):
    """Produce the OOF predictions by nested CV, then train the deployable model.

    `outer_folds` is a list of (repeat, fold, train_ids, test_ids) as produced by
    utils.repeated_kfold_patients. Each repetition is an independent patient-level
    K-fold partition; the deployable model does not depend on any outer partition
    and is therefore tuned and trained ONCE.

    The Optuna tuning of each outer fold uses ONLY the training part of that fold
    (inner CV): the outer test fold never takes part in hyperparameter selection.
    The inner CV seed is SEED+101+k+1000*r, which at r=0 reduces to SEED+101+k.

    Returns a DataFrame (index=record_id, columns=repeats).
    """
    reps = sorted({r for r, _, _, _ in outer_folds})
    oof = pd.DataFrame(np.nan, index=X.index, columns=reps, dtype=float)
    per_fold = []
    for r, k, tr_ids, te_ids in outer_folds:
        tr = list(X.index.intersection(tr_ids))
        te = list(X.index.intersection(te_ids))
        # Inner CV built only on the training part of the outer fold.
        inner_folds = kfold_patients(tr, seed=SEED + 101 + k + 1000 * r,
                                     n_folds=N_INNER_FOLDS)
        params, inner_rmse = tune_fn(X, y, inner_folds)
        preds = fitpred_fn(X, y, tr, te, params)
        oof.loc[te, r] = preds
        per_fold.append({"repeat": r, "fold": k, "params": params,
                         "inner_cv_rmse": inner_rmse})

    # Deployable model: tuning on an inner CV covering all patients, then a
    # refit on all patients. These parameters are NOT used for the OOF above.
    inner_full = kfold_patients(list(X.index), seed=SEED, n_folds=N_INNER_FOLDS)
    deploy_params, deploy_rmse = tune_fn(X, y, inner_full)
    final_fn(X, y, deploy_params, out_dir)

    with open(out_dir / f"best_params_{name}.json", "w") as f:
        json.dump({
            "deployable_params": deploy_params,
            "deployable_inner_cv_rmse": deploy_rmse,
            "per_outer_fold": per_fold,
            "n_outer_folds": len(outer_folds),
            "n_repeats": len(reps),
            "n_inner_folds": N_INNER_FOLDS,
            "n_trials": _n_trials(name),
        }, f, indent=2, default=str)
    return oof


def _n_trials(name):
    """Optuna trial budget for algorithm `name` (fallback: OPTUNA_N_TRIALS)."""
    return OPTUNA_N_TRIALS_BY_ALGO.get(name, OPTUNA_N_TRIALS)


def _make_study():
    return optuna.create_study(
        direction="minimize",
        sampler=optuna.samplers.TPESampler(seed=SEED),
        pruner=optuna.pruners.MedianPruner(
            n_startup_trials=OPTUNA_PRUNER_STARTUP_TRIALS,
            n_warmup_steps=OPTUNA_PRUNER_WARMUP_STEPS,
        ),
    )


def _maybe_prune(trial, rmses, step):
    """Report the running CV RMSE (mean over the folds already evaluated) to
    Optuna at fold `step`, and raise TrialPruned if the study's pruner judges the
    trial unpromising. No-op when no trial is supplied (CV outside tuning)."""
    if trial is None:
        return
    trial.report(float(np.mean(rmses)), step)
    if trial.should_prune():
        raise optuna.TrialPruned()


# ============================================================
# Linear Regression (no hyperparameter, so a plain outer CV = nested CV)
# ============================================================
def cv_linreg(X, y, folds):
    """Repeated K-fold CV producing the OOF predictions.

    `folds` is a list of (repeat, fold, train_ids, test_ids). Returns a
    DataFrame (index=record_id, columns=repeats)."""
    reps = sorted({r for r, _, _, _ in folds})
    oof = pd.DataFrame(np.nan, index=X.index, columns=reps, dtype=float)
    for r, _k, tr_ids, te_ids in folds:
        tr = X.index.intersection(tr_ids)
        te = X.index.intersection(te_ids)
        pipe = Pipeline([("pre", build_preprocessor(X.columns.tolist())),
                         ("lr", LinearRegression())])
        pipe.fit(X.loc[tr], y.loc[tr].values)
        oof.loc[te, r] = pipe.predict(X.loc[te])
    return oof


def fit_final_linreg(X, y, out_dir):
    pipe = Pipeline([("pre", build_preprocessor(X.columns.tolist())),
                     ("lr", LinearRegression())])
    pipe.fit(X, y.values)
    joblib.dump(pipe, out_dir / "linreg.joblib")


# ============================================================
# ElasticNet (with the shared preprocessor)
# ============================================================
def _make_elasticnet_pipe(feature_columns, params):
    return Pipeline([
        ("pre", build_preprocessor(feature_columns)),
        ("en", ElasticNet(**{**ELASTICNET_FIXED, **params})),
    ])


def _elasticnet_cv_rmse(params, X, y, folds, trial=None):
    rmses = []
    for step, (tr_ids, te_ids) in enumerate(folds):
        tr = X.index.intersection(tr_ids)
        te = X.index.intersection(te_ids)
        pipe = _make_elasticnet_pipe(X.columns.tolist(), params)
        pipe.fit(X.loc[tr], y.loc[tr].values)
        preds = pipe.predict(X.loc[te])
        rmses.append(float(np.sqrt(np.mean((preds - y.loc[te].values) ** 2))))
        _maybe_prune(trial, rmses, step)
    return float(np.mean(rmses))


def elasticnet_objective(trial, X, y, folds):
    params = {
        "alpha": trial.suggest_float("alpha", 1e-4, 10.0, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
    }
    return _elasticnet_cv_rmse(params, X, y, folds, trial)


def tune_elasticnet(X, y, folds):
    study = _make_study()
    study.optimize(lambda t: elasticnet_objective(t, X, y, folds),
                   n_trials=_n_trials("elasticnet"), timeout=OPTUNA_TIMEOUT,
                   show_progress_bar=False)
    return dict(study.best_params), study.best_value


def fitpred_elasticnet(X, y, tr, te, params):
    pipe = _make_elasticnet_pipe(X.columns.tolist(), params)
    pipe.fit(X.loc[tr], y.loc[tr].values)
    return pipe.predict(X.loc[te])


def final_elasticnet(X, y, params, out_dir):
    pipe = _make_elasticnet_pipe(X.columns.tolist(), params)
    pipe.fit(X, y.values)
    joblib.dump(pipe, out_dir / "elasticnet.joblib")


# ============================================================
# Random Forest (with the shared preprocessor)
# ============================================================
def _make_rf_pipe(feature_columns, params):
    return Pipeline([
        ("pre", build_preprocessor(feature_columns)),
        ("rf", RandomForestRegressor(**{**RF_FIXED, **params})),
    ])


def _rf_cv_rmse(params, X, y, folds, trial=None):
    rmses = []
    for step, (tr_ids, te_ids) in enumerate(folds):
        tr = X.index.intersection(tr_ids)
        te = X.index.intersection(te_ids)
        pipe = _make_rf_pipe(X.columns.tolist(), params)
        pipe.fit(X.loc[tr], y.loc[tr].values)
        preds = pipe.predict(X.loc[te])
        rmses.append(float(np.sqrt(np.mean((preds - y.loc[te].values) ** 2))))
        _maybe_prune(trial, rmses, step)
    return float(np.mean(rmses))


def rf_objective(trial, X, y, folds):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 600, step=100),
        "max_depth": trial.suggest_int("max_depth", 3, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", 1.0]),
    }
    return _rf_cv_rmse(params, X, y, folds, trial)


def tune_rf(X, y, folds):
    study = _make_study()
    study.optimize(lambda t: rf_objective(t, X, y, folds),
                   n_trials=_n_trials("rf"), timeout=OPTUNA_TIMEOUT,
                   show_progress_bar=False)
    return dict(study.best_params), study.best_value


def fitpred_rf(X, y, tr, te, params):
    pipe = _make_rf_pipe(X.columns.tolist(), params)
    pipe.fit(X.loc[tr], y.loc[tr].values)
    return pipe.predict(X.loc[te])


def final_rf(X, y, params, out_dir):
    pipe = _make_rf_pipe(X.columns.tolist(), params)
    pipe.fit(X, y.values)
    joblib.dump(pipe, out_dir / "rf.joblib")


# ============================================================
# XGBoost (shared preprocessor, to handle the one-hot encoding).
# Early stopping through a 90/10 sub-split of the training fold.
# ============================================================
def _xgb_fit_predict(X, y, tr_ids, te_ids, params):
    """Fit XGBoost on tr_ids (with an early-stopping sub-split), predict te_ids.

    The preprocessor is fitted on the early-stopping sub-training set, to avoid
    any leakage through the imputation and scaling statistics.
    """
    es_tr, es_va = _early_stop_split(tr_ids, seed=SEED)
    pre = build_preprocessor(X.columns.tolist())
    pre.fit(X.loc[es_tr])
    X_tr = pre.transform(X.loc[es_tr])
    X_va = pre.transform(X.loc[es_va])
    X_te = pre.transform(X.loc[te_ids])
    y_tr = y.loc[es_tr].values
    y_va = y.loc[es_va].values

    model = xgb.XGBRegressor(**params)
    model.fit(X_tr, y_tr, eval_set=[(X_va, y_va)], verbose=False)
    return model.predict(X_te), model, pre


def _xgboost_cv_rmse(params, X, y, folds, trial=None):
    rmses = []
    for step, (tr_ids, te_ids) in enumerate(folds):
        tr = X.index.intersection(tr_ids)
        te = X.index.intersection(te_ids)
        preds, _, _ = _xgb_fit_predict(X, y, list(tr), list(te), params)
        rmses.append(float(np.sqrt(np.mean((preds - y.loc[te].values) ** 2))))
        _maybe_prune(trial, rmses, step)
    return float(np.mean(rmses))


def xgboost_objective(trial, X, y, folds):
    params = {
        **XGBOOST_FIXED,
        "n_estimators": 2000,
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 1e-2, 10, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10, log=True),
        "gamma": trial.suggest_float("gamma", 1e-3, 5.0, log=True),
    }
    return _xgboost_cv_rmse(params, X, y, folds, trial)


def tune_xgboost(X, y, folds):
    study = _make_study()
    study.optimize(lambda t: xgboost_objective(t, X, y, folds),
                   n_trials=_n_trials("xgboost"), timeout=OPTUNA_TIMEOUT,
                   show_progress_bar=False)
    final_params = {**XGBOOST_FIXED, "n_estimators": 2000, **study.best_params}
    return final_params, study.best_value


def fitpred_xgboost(X, y, tr, te, params):
    preds, _, _ = _xgb_fit_predict(X, y, list(tr), list(te), params)
    return preds


def final_xgboost(X, y, params, out_dir):
    # Preprocessor fitted on the es_tr part of the global split, consistent with
    # the booster.
    es_tr, es_va = _early_stop_split(list(X.index), seed=SEED + 1)
    pre = build_preprocessor(X.columns.tolist())
    pre.fit(X.loc[es_tr])
    X_tr = pre.transform(X.loc[es_tr])
    X_va = pre.transform(X.loc[es_va])
    final = xgb.XGBRegressor(**params)
    final.fit(X_tr, y.loc[es_tr].values, eval_set=[(X_va, y.loc[es_va].values)], verbose=False)
    final.save_model(str(out_dir / "xgboost.json"))
    # XGBoost-specific preprocessor, fitted on es_tr only, hence different from
    # the final MLP/LinReg one.
    joblib.dump(pre, out_dir / "preprocessor_xgboost.joblib")


# ============================================================
# CatBoost
# ============================================================
def _cb_fit_predict(X, y, tr_ids, te_ids, params):
    """Fit CatBoost on tr_ids (with an early-stopping sub-split), predict te_ids."""
    cat_idx = [X.columns.get_loc(c) for c in CATEGORICAL_FEATURES if c in X.columns]
    X_cb = _prep_catboost_df(X)
    es_tr, es_va = _early_stop_split(tr_ids, seed=SEED)
    model = CatBoostRegressor(**params)
    model.fit(
        Pool(X_cb.loc[es_tr], y.loc[es_tr].values, cat_features=cat_idx),
        eval_set=Pool(X_cb.loc[es_va], y.loc[es_va].values, cat_features=cat_idx),
    )
    return model.predict(X_cb.loc[te_ids]), model


def _catboost_cv_rmse(params, X, y, folds, trial=None):
    rmses = []
    for step, (tr_ids, te_ids) in enumerate(folds):
        tr = X.index.intersection(tr_ids)
        te = X.index.intersection(te_ids)
        preds, _ = _cb_fit_predict(X, y, list(tr), list(te), params)
        rmses.append(float(np.sqrt(np.mean((preds - y.loc[te].values) ** 2))))
        _maybe_prune(trial, rmses, step)
    return float(np.mean(rmses))


def catboost_objective(trial, X, y, folds):
    params = {
        **CATBOOST_FIXED,
        "iterations": 2000,
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 3, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-2, 10, log=True),
        "random_strength": trial.suggest_float("random_strength", 1e-2, 10, log=True),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
    }
    return _catboost_cv_rmse(params, X, y, folds, trial)


def tune_catboost(X, y, folds):
    study = _make_study()
    study.optimize(lambda t: catboost_objective(t, X, y, folds),
                   n_trials=_n_trials("catboost"), timeout=OPTUNA_TIMEOUT,
                   show_progress_bar=False)
    final_params = {**CATBOOST_FIXED, "iterations": 2000, **study.best_params}
    return final_params, study.best_value


def fitpred_catboost(X, y, tr, te, params):
    preds, _ = _cb_fit_predict(X, y, list(tr), list(te), params)
    return preds


def final_catboost(X, y, params, out_dir):
    es_tr, es_va = _early_stop_split(list(X.index), seed=SEED + 1)
    cat_idx = [X.columns.get_loc(c) for c in CATEGORICAL_FEATURES if c in X.columns]
    X_cb = _prep_catboost_df(X)
    final = CatBoostRegressor(**params)
    final.fit(
        Pool(X_cb.loc[es_tr], y.loc[es_tr].values, cat_features=cat_idx),
        eval_set=Pool(X_cb.loc[es_va], y.loc[es_va].values, cat_features=cat_idx),
    )
    final.save_model(str(out_dir / "catboost.cbm"))


# ============================================================
# MLP
# ============================================================
class MLP(nn.Module):
    def __init__(self, n_in, hidden_sizes, dropout):
        super().__init__()
        layers, prev = [], n_in
        for h in hidden_sizes:
            layers += [nn.Linear(prev, h), nn.ReLU(), nn.Dropout(dropout)]
            prev = h
        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x).squeeze(-1)


def _to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32, device=DEVICE)


def _train_mlp(X_tr, y_tr, X_va, y_va, params):
    """MLP training loop with early stopping. Returns (model, best_val_rmse)."""
    torch.manual_seed(SEED)
    model = MLP(X_tr.shape[1], params["hidden_sizes"], params["dropout"]).to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=params["lr"],
                           weight_decay=params["weight_decay"])
    loss_fn = nn.MSELoss()
    X_tr_t, y_tr_t = _to_tensor(X_tr), _to_tensor(y_tr)
    X_va_t = _to_tensor(X_va)
    n = X_tr_t.shape[0]

    best_state, best_val, patience = None, float("inf"), 0
    for _ in range(MLP_MAX_EPOCHS):
        model.train()
        perm = torch.randperm(n, device=DEVICE)
        for i in range(0, n, MLP_BATCH_SIZE):
            idx = perm[i:i + MLP_BATCH_SIZE]
            opt.zero_grad()
            loss = loss_fn(model(X_tr_t[idx]), y_tr_t[idx])
            loss.backward()
            opt.step()
        model.eval()
        with torch.no_grad():
            va_pred = model(X_va_t).cpu().numpy()
        va_rmse = float(np.sqrt(np.mean((va_pred - y_va) ** 2)))
        if va_rmse < best_val - 1e-5:
            best_val = va_rmse
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
            patience = 0
        else:
            patience += 1
            if patience >= MLP_PATIENCE:
                break
    model.load_state_dict(best_state)
    return model, best_val


def _mlp_fit_predict(X, y, tr, te, params):
    """Fit the MLP on the IDs `tr` (internal preprocessor and early stopping),
    then predict `te`.

    The preprocessor is fitted on the early-stopping sub-training set
    (es_tr, a subset of tr), never on `te`.
    """
    es_tr, es_va = _early_stop_split(tr, seed=SEED)
    pre = build_preprocessor(X.columns.tolist())
    pre.fit(X.loc[es_tr])
    X_tr = pre.transform(X.loc[es_tr]).astype(np.float32)
    X_va = pre.transform(X.loc[es_va]).astype(np.float32)
    X_te = pre.transform(X.loc[te]).astype(np.float32)
    y_tr = y.loc[es_tr].values.astype(np.float32)
    y_va = y.loc[es_va].values.astype(np.float32)

    model, _ = _train_mlp(X_tr, y_tr, X_va, y_va, params)
    model.eval()
    with torch.no_grad():
        return model(_to_tensor(X_te)).cpu().numpy()


def _mlp_cv_rmse(X, y, folds, params, trial=None):
    """Mean CV RMSE, with the preprocessor fitted INSIDE each fold."""
    rmses = []
    for step, (tr_ids, te_ids) in enumerate(folds):
        tr = list(X.index.intersection(tr_ids))
        te = list(X.index.intersection(te_ids))
        preds = _mlp_fit_predict(X, y, tr, te, params)
        y_te = y.loc[te].values.astype(np.float32)
        rmses.append(float(np.sqrt(np.mean((preds - y_te) ** 2))))
        _maybe_prune(trial, rmses, step)
    return float(np.mean(rmses))


def _mlp_params_from_trial(best):
    """Rebuild a usable params dict from Optuna's best_params."""
    n_layers = best["n_layers"]
    return {
        "hidden_sizes": [best[f"h{i}"] for i in range(n_layers)],
        "dropout": best["dropout"],
        "lr": best["lr"],
        "weight_decay": best["weight_decay"],
    }


def mlp_objective(trial, X, y, folds):
    n_layers = trial.suggest_int("n_layers", 1, 3)
    hidden = [trial.suggest_categorical(f"h{i}", [16, 32, 64, 128]) for i in range(n_layers)]
    params = {
        "hidden_sizes": hidden,
        "dropout": trial.suggest_float("dropout", 0.0, 0.5),
        "lr": trial.suggest_float("lr", 1e-4, 1e-2, log=True),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
    }
    return _mlp_cv_rmse(X, y, folds, params, trial)


def tune_mlp(X, y, folds):
    study = _make_study()
    study.optimize(lambda t: mlp_objective(t, X, y, folds),
                   n_trials=_n_trials("mlp"), timeout=OPTUNA_TIMEOUT,
                   show_progress_bar=False)
    return _mlp_params_from_trial(study.best_params), study.best_value


def fitpred_mlp(X, y, tr, te, params):
    return _mlp_fit_predict(X, y, tr, te, params)


def final_mlp(X, y, params, out_dir):
    # Preprocessor fitted on everything (deployment); 90/10 sub-split for early
    # stopping.
    pre = build_preprocessor(X.columns.tolist())
    pre.fit(X)
    # NB: overwrites the preprocessor.joblib saved earlier (identical, deterministic).
    joblib.dump(pre, out_dir / "preprocessor.joblib")
    X_all = pre.transform(X).astype(np.float32)
    y_all = y.values.astype(np.float32)
    es_tr, es_va = _early_stop_split(np.arange(len(X_all)), seed=SEED + 2)
    model, _ = _train_mlp(X_all[es_tr], y_all[es_tr], X_all[es_va], y_all[es_va], params)
    torch.save({"state_dict": model.state_dict(),
                "n_in": X_all.shape[1],
                "params": params}, out_dir / "mlp.pt")


# ============================================================
# Main
# ============================================================
def main():
    print("=" * 70)
    print("TRAINING - 6 algorithms x every endpoint - patient-level NESTED CV")
    print(f"  Outer CV: {N_FOLDS} folds (OOF)  |  Inner CV: {N_INNER_FOLDS} folds (tuning)")
    print(f"PyTorch device: {DEVICE}")
    print("=" * 70)
    ensure_dir(MODELS_DIR)

    X_full, y_full, src_full = load_prep()
    print(f"[ok] Loaded: {X_full.shape[0]} patients x {X_full.shape[1]} features")

    for endpoint in y_full.columns:
        print(f"\n{'-' * 70}\n>>> Endpoint: {endpoint}\n{'-' * 70}")
        X, y = get_endpoint_data(X_full, y_full[endpoint])
        n = len(X)
        # EVALUATION index = real targets (Case 1) only. Targets imputed by the
        # trajectory model stay in X/y to TRAIN (training folds), but are never
        # counted in the OOF metrics.
        eval_idx = real_eval_index(X, src_full, endpoint)
        n_real = len(eval_idx)
        print(f"  Usable patients: {n}  ({n_real} real targets evaluated, "
              f"{n - n_real} model-imputed - training only)")
        if n < 30:
            print(f"  ! Too few patients (< 30) - skipping {endpoint}")
            continue
        if n_real == 0:
            print(f"  ! No real target for {endpoint} - OOF metrics not interpretable.")

        out_dir = ensure_dir(MODELS_DIR / endpoint)

        # Preprocessor fitted on all patients, for SHAP and deployment (the MLP
        # step saves an identical one).
        pre_full = build_preprocessor(X.columns.tolist())
        pre_full.fit(X)
        joblib.dump(pre_full, out_dir / "preprocessor.joblib")

        # Patient-level outer folds - the same folds for every algorithm.
        # N_REPEATS independent partitions; at N_REPEATS=1 this is exactly
        # kfold_patients(X.index, seed=SEED, n_folds=N_FOLDS).
        folds = repeated_kfold_patients(X.index, seed=SEED, n_folds=N_FOLDS,
                                        n_repeats=N_REPEATS)
        fold_assignment = {(r, pid): f for r, f, _, te in folds for pid in te}

        # ----- LinReg (no tuning) -----
        print(f"  [1/6] Linear Regression (baseline) - {N_FOLDS}-fold CV"
              f"{f' x{N_REPEATS} repetitions' if N_REPEATS > 1 else ''}...")
        oof_lr = cv_linreg(X, y, folds)
        fit_final_linreg(X, y, out_dir)
        report_oof("LinReg", y, oof_lr, eval_idx)

        # ----- ElasticNet -----
        print(f"  [2/6] ElasticNet - nested CV (Optuna {_n_trials('elasticnet')} trials)...")
        oof_en = run_nested_cv("elasticnet", tune_elasticnet, fitpred_elasticnet,
                               final_elasticnet, X, y, folds, out_dir)
        report_oof("ElasticNet", y, oof_en, eval_idx)

        # ----- Random Forest -----
        print(f"  [3/6] Random Forest - nested CV (Optuna {_n_trials('rf')} trials)...")
        oof_rf = run_nested_cv("rf", tune_rf, fitpred_rf,
                               final_rf, X, y, folds, out_dir)
        report_oof("RandomForest", y, oof_rf, eval_idx)

        # ----- XGBoost -----
        print(f"  [4/6] XGBoost - nested CV (Optuna {_n_trials('xgboost')} trials)...")
        oof_xgb = run_nested_cv("xgboost", tune_xgboost, fitpred_xgboost,
                                final_xgboost, X, y, folds, out_dir)
        report_oof("XGBoost", y, oof_xgb, eval_idx)

        # ----- CatBoost -----
        print(f"  [5/6] CatBoost - nested CV (Optuna {_n_trials('catboost')} trials)...")
        oof_cb = run_nested_cv("catboost", tune_catboost, fitpred_catboost,
                               final_catboost, X, y, folds, out_dir)
        report_oof("CatBoost", y, oof_cb, eval_idx)

        # ----- MLP -----
        print(f"  [6/6] MLP - nested CV (Optuna {_n_trials('mlp')} trials)...")
        oof_mlp = run_nested_cv("mlp", tune_mlp, fitpred_mlp,
                                final_mlp, X, y, folds, out_dir)
        report_oof("MLP", y, oof_mlp, eval_idx)

        # Dump the OOF predictions in LONG format, one row per (patient,
        # repetition). At N_REPEATS=1 there is a single row per patient and the
        # `repeat` column is 0 everywhere, so the file is a strict superset of
        # the single-partition format and readers ignoring `repeat` stay
        # correct. Beyond that, EVERY consumer must join on (record_id, repeat):
        # a merge on record_id alone would silently produce a cartesian product.
        src_col = (src_full[endpoint].reindex(X.index)
                   if src_full is not None else pd.Series("unknown", index=X.index))
        preds = {"linreg": oof_lr, "elasticnet": oof_en, "rf": oof_rf,
                 "xgboost": oof_xgb, "catboost": oof_cb, "mlp": oof_mlp}
        preds = {k: _as_repeat_frame(v) for k, v in preds.items()}
        blocks = []
        for r in range(N_REPEATS):
            block = pd.DataFrame({
                "record_id": list(X.index),
                "repeat": r,
                "fold": [fold_assignment[(r, pid)] for pid in X.index],
                "source": src_col.values,      # real (evaluated) / model (training only)
                "y_true": y.values,
            })
            for algo, frame in preds.items():
                block[algo] = frame[r].values
            blocks.append(block)
        pd.concat(blocks, ignore_index=True).to_csv(
            out_dir / "oof_predictions.csv", index=False)

    print(f"\n[done] All models trained. Results in {MODELS_DIR}/")


if __name__ == "__main__":
    main()
